// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyiylhgzqwtmjqofjayu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5aXlsaGd6cXd0bWpxb2ZqYXl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0ODM0OTMsImV4cCI6MjA2MTA1OTQ5M30.Xmi2fVA3nEzsx3xodq2j29Js7rKSomSClJzJ3TCoSJM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);